version: '3'
services:
  web:
    build: ./web
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=development

  api:
    build: ./api
    ports:
      - "8081:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27018:27017"
